# Generated by Django 5.0.4 on 2024-04-10 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annexe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Annexe',
                'verbose_name_plural': 'Annexes',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('conformite', models.FloatField(default=0)),
                ('veracite', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Exigence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Exigence',
                'verbose_name_plural': 'Exigences',
            },
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('conformite', models.FloatField(default=0)),
                ('veracite', models.IntegerField(default=0)),
                ('annexeA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditApp.annexe')),
            ],
            options={
                'verbose_name': 'Chapitre',
                'verbose_name_plural': 'Chapitres',
            },
        ),
        migrations.CreateModel(
            name='Critere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('conformite', models.FloatField(default=0)),
                ('veracite', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditApp.article')),
                ('exigence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditApp.exigence')),
            ],
            options={
                'verbose_name': 'Critere',
                'verbose_name_plural': 'Criteres',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='exigence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditApp.exigence'),
        ),
        migrations.CreateModel(
            name='SousArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('conformite', models.FloatField(default=0)),
                ('veracite', models.IntegerField(default=0)),
                ('critere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditApp.critere')),
                ('exigence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditApp.exigence')),
            ],
            options={
                'verbose_name': 'SousArticle',
                'verbose_name_plural': 'SousArticles',
            },
        ),
        migrations.CreateModel(
            name='SousChapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('conformite', models.FloatField(default=0)),
                ('veracite', models.IntegerField(default=0)),
                ('annexe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditApp.annexe')),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditApp.chapitre')),
            ],
            options={
                'verbose_name': 'SousChapitre',
                'verbose_name_plural': 'SousChapitres',
            },
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('conformite', models.FloatField(default=0)),
                ('veracite', models.IntegerField(default=0)),
                ('annexe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditApp.annexe')),
                ('sousChapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditApp.souschapitre')),
            ],
            options={
                'verbose_name': 'Mesure',
                'verbose_name_plural': 'Mesures',
            },
        ),
    ]
