# Generated by Django 5.0.4 on 2024-05-17 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditApp', '0002_annexe_article_exigence_chapitre_critere_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapitre',
            name='conformite',
        ),
        migrations.RemoveField(
            model_name='chapitre',
            name='veracite',
        ),
        migrations.RemoveField(
            model_name='souschapitre',
            name='conformite',
        ),
        migrations.RemoveField(
            model_name='souschapitre',
            name='veracite',
        ),
    ]
