# Generated by Django 5.0.4 on 2024-05-17 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditApp', '0003_remove_chapitre_conformite_remove_chapitre_veracite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='NoteCible',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ReponseSousChapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('sous_chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditApp.souschapitre')),
            ],
        ),
    ]
