# Generated by Django 5.0.4 on 2024-05-17 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditApp', '0004_chapitre_notecible_reponsesouschapitre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='souschapitre',
            name='annexe',
        ),
    ]
