# Generated by Django 5.0.4 on 2024-05-28 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditApp', '0005_remove_souschapitre_annexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='numero',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='souschapitre',
            name='numero',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='souschapitre',
            name='chapitre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitre', to='auditApp.chapitre'),
        ),
    ]
